#!/usr/bin/env python3
"""Generate data/wave4.json (wave-4 research pass, Sep 10 2026).

50 new businesses discovered this session from real retrievals: Yelp indexed
extracts, Thumbtack indexes, Reddit threads, Yellow Pages, Yahoo Local, and
direct reads of business websites and CSLB license detail pages.

Verification discipline (no hallucinations):
- Every business name, star sample, quote and phone below appears verbatim in
  a retrieval captured this session; the source id points at that retrieval.
- Five licenses were read directly on cslb.ca.gov this session (sources
  101-105): 698806, 954813, 876212, 1006178, 1057927. Only 1006178 attaches
  to a new wave-4 entry (Integrity First): it is active C-36 and the record
  name matches. 1057927 resolved to a DIFFERENTLY NAMED Hayward "B" entity
  (Ortega's Bay Area General Construction Inc) than the marketing page that
  printed it (Repipe Champions), so it is recorded as a flag, never attached.
  698806/954813/876212 match EXISTING wave-1/3 entries and are attached by
  scripts/patch_wave4_licenses.py after the merge (append-only merge rules).
- Where identity, area or license is unproven, the field is null and the
  limitation is an explicit gap. Nothing is promoted to the master list.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESEARCHED = "2026-09-10"

# New sources for this wave (existing dataset uses ids 1..100).
SOURCES = [
    {"id": 101, "title": "CSLB · 698806 Magic Plumbing",
     "url": "https://www.cslb.ca.gov/OnlineServices/CheckLicenseII/LicenseDetail.aspx?LicNum=698806",
     "kind": "government", "access": "page", "checkedAt": RESEARCHED,
     "note": "Direct read 09/10/2026: MAGIC PLUMBING dba MAGIC PLUMBING HEATING & COOLING, SF 94114; current and active; C36 + C20; expires 03/31/2027."},
    {"id": 102, "title": "CSLB · 954813 24/7 Rooter and Plumbing Services Inc",
     "url": "https://www.cslb.ca.gov/OnlineServices/CheckLicenseII/LicenseDetail.aspx?LicNum=954813",
     "kind": "government", "access": "page", "checkedAt": RESEARCHED,
     "note": "Direct read 09/10/2026: 24/7 ROOTER AND PLUMBING SERVICES INC dba A & R PLUMBING, SF 94124; current and active; C36 + D56 + A; expires 11/30/2026."},
    {"id": 103, "title": "CSLB · 876212 A B Plumbing",
     "url": "https://www.cslb.ca.gov/OnlineServices/CheckLicenseII/LicenseDetail.aspx?LicNum=876212",
     "kind": "government", "access": "page", "checkedAt": RESEARCHED,
     "note": "Direct read 09/10/2026: A B PLUMBING, 12909 Skyline Blvd, Oakland 94619; current and active; C36; expires 04/30/2028; bond shows cancellation date 10/03/2026; workers-comp exemption (no employees)."},
    {"id": 104, "title": "CSLB · 1006178 Integrity First Plumbing Inc",
     "url": "https://www.cslb.ca.gov/OnlineServices/CheckLicenseII/LicenseDetail.aspx?LicNum=1006178",
     "kind": "government", "access": "page", "checkedAt": RESEARCHED,
     "note": "Direct read 09/10/2026: INTEGRITY FIRST PLUMBING INC, 1485 Bayshore Blvd 457, SF 94124; current and active; C36; expires 08/31/2027."},
    {"id": 105, "title": "CSLB · 1057927 Ortega's Bay Area General Construction Inc",
     "url": "https://www.cslb.ca.gov/OnlineServices/CheckLicenseII/LicenseDetail.aspx?LicNum=1057927",
     "kind": "government", "access": "page", "checkedAt": RESEARCHED,
     "note": "Direct read 09/10/2026: the number printed on repipechampions.com resolves to ORTEGA'S BAY AREA GENERAL CONSTRUCTION INC, Hayward — active B (General Building), NOT a C-36 plumbing license and not the marketing name."},
    {"id": 106, "title": "Heise's Plumbing · drain-cleaning page with dated job check-ins",
     "url": "https://www.heisesplumbing.com/drain-cleaning/",
     "kind": "business", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Company-published check-ins (Feb–Mar 2026) describing cabled shower/tub drains and tub-stopper work at SF residences."},
    {"id": 107, "title": "Yelp · Plumber near Outer Sunset, SF (Sep 2026 indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=plumber&find_loc=Outer+Sunset%2C+San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: True-Tech (5.0/116 sample, Verified License badge), Legend Plumbing & Drain (5.0/20, sponsored), Pham's Plumbing (4.8/22), WB Plumbing Supply."},
    {"id": 108, "title": "Yelp · 24 hour plumber near Outer Sunset (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=24+hour+plumber&find_loc=Outer+Sunset%2C+San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Maverick Water Heaters 5.0(31), ASAP Plumbing Pros 4.8(119), X-Ray Plumbing And Drain 5.0(48), Allied Bay Contractors 5.0(1)."},
    {"id": 109, "title": "Yelp · Best 10 Plumbing near Outer Sunset (indexed extract A)",
     "url": "https://www.yelp.com/search?cflt=plumbing&find_loc=Outer+Sunset,+San+Francisco,+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract listing George Salet, Whistle, Urgent Rooter, Erwyn's, Citywide, Advanced, Genteel, Plumbing Pure, Kenneth Asire, Pipe Whisperer, Works."},
    {"id": 110, "title": "Yelp · Best 10 Plumbing near Outer Sunset (indexed extract B)",
     "url": "https://www.yelp.com/search?cflt=plumbing&find_loc=outer+sunset%2C+san+francisco%2C+ca",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Marco's Plumbing (16 reviews, started 2013), Chosen Rooter, Heise's, Expert Plumbing Solutions."},
    {"id": 111, "title": "Yelp · Plumbing San Francisco (May 2026 indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Plumbing&find_loc=San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: F&A Plumbing&Rooter 4.9(150, Pacifica), Portola Plumbing Services with bathtub installation/repair tags."},
    {"id": 112, "title": "Yelp · Drain Cleaning San Francisco (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Drain+Cleaning&find_loc=San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Urban Bay Engineering (sponsored, drain repair), 'Discount Plumbing San Francisco' naming variant, Rooter Hero."},
    {"id": 113, "title": "Yelp · Drywall Contractor San Francisco (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Drywall+Contractor&find_loc=San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: A1 Drywall 4.7(68), Paint Studio SF 4.6(71), Benjamin Shaw 4.9(32), Northwest Builders & Renovation 3.3(8); ceiling/wall opening quote."},
    {"id": 114, "title": "Yelp · Drywall Repair And Paint San Francisco (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Drywall+Repair+And+Paint&find_loc=San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Carlos' Painting & Handyman 4.9(123), Toms Painters, Amador's, Ryno."},
    {"id": 115, "title": "Yelp biz · Sunset Handyman (indexed profile extract)",
     "url": "https://www.yelp.com/biz/sunset-handyman-san-francisco-3",
     "kind": "business", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed profile: Sunset Handyman 5.0(4), claimed; framing/finish carpenter 15+ years; 650-430-8565; long mirror-hanging review."},
    {"id": 116, "title": "Yelp · Handyman Outer Sunset (Aug 2026 indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Handyman&find_loc=Outer+Sunset%2C+San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Octavio Handyman 5.0(6), Handyman Heroes 4.7(398), Reasonably Honest Mike's 4.9(90)."},
    {"id": 117, "title": "Yelp · Handyman San Francisco (Sep 2026 indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Handyman&find_loc=San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Fullhouse Remodeling & Handyman 4.8(20), Handlify 4.9(151), Paul Woodford Services 4.7(83)."},
    {"id": 118, "title": "Yelp biz · San Francisco Handyman Services (indexed profile extract)",
     "url": "https://www.yelp.com/biz/san-francisco-handyman-services-san-francisco",
     "kind": "business", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed profile: 5.0(3), claimed; family-owned; 40+ years; drywall installation and repair listed among services."},
    {"id": 119, "title": "Yelp biz · Mike's Water Damage (indexed profile extract)",
     "url": "https://www.yelp.com/biz/mike-s-water-damage-san-francisco",
     "kind": "business", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed profile: 4.9(72), claimed, SF 94107, (650) 514-1414; multiple ceiling water-damage reviews incl. a property manager."},
    {"id": 120, "title": "Yelp · Ceiling Leak Repair San Francisco (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Ceiling+Leak+Repair&find_loc=San+Francisco,+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Swift Restoration, All Action Water Damage 4.9(126, Burlingame), Mike's Water Damage drywall-repair quote."},
    {"id": 121, "title": "Yelp · Water ceiling leak San Francisco (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=water+ceiling+leak&find_loc=San+Francisco,+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Dry Kings Restoration 4.8(122, 420 Berry St Mission Bay, Verified License), SAFENEST 4.9(78), Max Restoration 5.0(32), Absolute Sanitation Plumbing and Restoration 4.8(53)."},
    {"id": 122, "title": "Thumbtack · Best plumbing services San Francisco (indexed extract)",
     "url": "https://www.thumbtack.com/ca/san-francisco/affordable-plumbing-services",
     "kind": "directory", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Deals on Wheels Top Pro 4.9(285); Antonio's Plumbing & Rooter Service 4.9(295); Ayala's; ASAP; Maximus; Bright Ideas; Navta."},
    {"id": 123, "title": "Thumbtack · Plumbers near South San Francisco (indexed extract)",
     "url": "https://www.thumbtack.com/ca/south-san-francisco/plumbing",
     "kind": "directory", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Antonio (314 reviews), Alpha Plumbing Solutions 4.8(10), ASAP 5.0(325), The Route To Your Problem 4.9(66), Dom's 5.0(7), Dr. Drain, LGM."},
    {"id": 124, "title": "Thumbtack · 24 hour plumbers San Francisco (indexed extract)",
     "url": "https://www.thumbtack.com/ca/san-francisco/24-hour-plumbers",
     "kind": "directory", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Natan plumbing 5.0(13, serves SF), Antonio 745 hires serves SF, Plumbing Bay Area 4.8(18, serves SF)."},
    {"id": 125, "title": "Thumbtack · Plumbers San Francisco (indexed extract + JSON-LD)",
     "url": "https://www.thumbtack.com/ca/san-francisco/plumbing/",
     "kind": "directory", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Costello's Plumbing JSON-LD rating 4.80(177); JN and Son Plumbing review mentions; Antonio 4.92(171) JSON-LD with Sohela S. review."},
    {"id": 126, "title": "Reddit · r/PlumberSanFrancisco top-10 thread (indexed extract)",
     "url": "https://www.reddit.com/r/PlumberSanFrancisco/comments/1ostnel/top_10_best_plumbers_in_san_francisco_fight_me_in/",
     "kind": "directory", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Poster self-describes as a licensed SF plumber. Table lists CSLB numbers: Magic 698806, Ace 829071, 24/7 Rooter 954813, Lutz 503971, A.B. 876212, Advanced 1009195, Integrity First 1006178. A comment recommends Economy Plumbing."},
    {"id": 127, "title": "Reddit · r/sanfrancisco handyman/plumber thread (indexed extract)",
     "url": "https://www.reddit.com/r/sanfrancisco/comments/16o0t6h/any_good_handymansplumber_in_sf/",
     "kind": "directory", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "2023 thread: 'Esther from A.B. Plumbing' recommendation with ab-plumbing.com link; one user finds Atlas overpriced; Crusader Plumbing number posted."},
    {"id": 128, "title": "Yahoo Local · Best plumbers in San Francisco (indexed extract)",
     "url": "https://local.yahoo.com/plumbing/article/best-plumbing-companies-san-francisco-california-110033609.html",
     "kind": "directory", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Editorial listicle (Mar 2026): Ace, George Salet, Wizard Plumbing & Drain (same-day; EJ Home Services partnership), Genteel."},
    {"id": 129, "title": "Yellow Pages · San Francisco plumber list (indexed extract)",
     "url": "https://www.yellowpages.com/san-francisco-ca/san-francisco-plumber",
     "kind": "directory", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: San Francisco Plumbing Repairs, 645 Judah St 94122, (415) 570-8420; Gateway Rooter & Plumbing Inc; plus 94122 storefront brands captured in wave 3."},
    {"id": 130, "title": "Yellow Pages · Central San Francisco plumbers (indexed extract)",
     "url": "https://www.yellowpages.com/central-san-francisco-san-francisco-ca/plumbers",
     "kind": "directory", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed extract: Tommy Tung 1354 31st Ave; Master Rooter PO Box variant; Pro Plumbing & Fire Sprinkler 1814 40th Ave; Gateway Rooter mention."},
    {"id": 131, "title": "5 Star Plumbing & Rooter · repiping page (indexed extract)",
     "url": "https://fivestarplumbingsf.com/services/repiping/",
     "kind": "business", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Marketing page: galvanized-steel repipes and partial repipes; names Sunset among older SF neighborhoods served; shows License (996627), 811 San Jose Ave, (415) 724-7083."},
    {"id": 132, "title": "Chosen Rooter & Plumbing · house repiping page (indexed extract)",
     "url": "https://chosenrooter.com/house-repiping/",
     "kind": "business", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Marketing page: PEX replacement of outdated copper or galvanized steel pipes; 628-209-6700; claims 12 years / 18,000+ issues solved."},
    {"id": 133, "title": "Repipe Champions · South San Francisco page (indexed extract)",
     "url": "https://repipechampions.com/repipe/south-san-francisco/",
     "kind": "business", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Marketing page printing 'CSLB #1057927' and a 4.9 Google rating; galvanized/PEX repipe focus; South San Francisco and North Peninsula scope."},
    {"id": 134, "title": "Repipe Specialists · San Francisco local services (indexed extract)",
     "url": "https://san-francisco.repipe.com/local-services.html",
     "kind": "business", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Marketing page: SF-region galvanized pipe replacement; hosted testimonials incl. 'Saved me thousands of dollars by not requiring I remove the shower walls.'"},
    {"id": 135, "title": "Legend Plumbing and Drain · official site (indexed extract)",
     "url": "https://legendplumbingsf.com/",
     "kind": "business", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Business site JSON-LD: San Francisco 94117, (415) 298-5181, open 7 AM–8 PM daily."},
    {"id": 136, "title": "True-Tech Water and Plumbing · Yelp profile (indexed extract)",
     "url": "https://www.yelp.com/biz/true-tech-water-and-plumbing-san-jose",
     "kind": "business", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Yelp profile is San-Jose based: truetechwp.com, (408) 446-3334; page text notes re-establishment by a new owner in 2023."},
    {"id": 137, "title": "BizProfile · F&A Plumbing & Rooter filing (indexed extract)",
     "url": "https://www.bizprofile.net/ca/pacifica/f-a-plumbing-rooter",
     "kind": "directory", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Third-party corporate filing summary: F&a Plumbing & Rooter, Pacifica, incorporated 01/12/2016, active standing."},
    {"id": 138, "title": "Yelp biz · F&A Plumbing&Rooter (indexed profile extract)",
     "url": "https://www.yelp.com/biz/f-and-a-plumbing-and-rooter-pacifica-3",
     "kind": "business", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed profile: 50 W Manor Dr Ste 1495, Pacifica 94044, (415) 728-5213; services incl. earthquake safety, drains, gas/water/sewer lines; est. 2012; Verified License badge."},
    {"id": 139, "title": "Economy Plumbing · official services page",
     "url": "https://economysf.com/services/",
     "kind": "business", "access": "page", "checkedAt": RESEARCHED,
     "note": "Direct read 09/10/2026: 'We serve Daly City, Mission area and San Francisco.' Live booking calendar rendered September 2026 dates; 24/7 service advertised."},
    {"id": 140, "title": "Yelp biz · Legend Plumbing & Drain (indexed profile extract)",
     "url": "https://www.yelp.com/biz/legend-plumbing-and-drain-san-francisco",
     "kind": "business", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed profile: San Francisco 94117, (628) 218-5447, Verified License badge; photo update 'waste system on a single family home in Pacifica'."},
]

# Compact business rows: id, name, area, areaText, discovery source, excerpt, discovery text,
# extra gaps; optional kwargs: website, websiteSource, phone, phoneSource, flags, reviewIds,
# platformLinks, extra claims, license.
ROWS = [
    # ---------------- Plumbing — discovery with verification notes ----------------
    dict(id="true-tech", name="True-Tech Water and Plumbing", area="outside",
         areaText="Appears on an indexed Outer Sunset plumber page as a promoted listing; its Yelp profile places the business in San Jose.",
         claims=[("Discovery", 107,
                  "Indexed Outer Sunset plumber page shows True-Tech Water and Plumbing at 5.0 across about 116 reviews with a Yelp verified-license badge.",
                  "True-Tech Water and Plumbing 5.0 (116 reviews) Verified License"),
                 ("Identity", 136,
                  "Yelp profile places True-Tech in San Jose with a (408) phone and notes re-establishment under a new owner in 2023.",
                  "true-tech-water-and-plumbing-san-jose · (408) 446-3334 · established by a new owner in 2023")],
         website="https://truetechwp.com/", websiteSource=136,
         phone="(408) 446-3334", phoneSource=136,
         flags=[{"level": "notice",
                 "text": "Based in San Jose per its own Yelp profile (408 area code) while appearing as a promoted result on an Outer Sunset page — Outer Sunset dispatch distance makes coverage unlikely until confirmed.",
                 "sources": [107, 136]}],
         gaps=["No exact seized-overflow extraction case verified.",
               "CSLB number not captured this pass.",
               "Outer Sunset coverage unconfirmed; base is San Jose."]),
    dict(id="legend", name="Legend Plumbing & Drain", area="sunset",
         areaText="San Francisco business (94117) per its own site and Yelp profile; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 140,
                  "Yelp profile for Legend Plumbing & Drain shows a Verified License badge and a 5.0 star sample with waste-system work in Pacifica.",
                  "Verified License — Yelp confirmed a business or employee license · (628) 218-5447"),
                 ("Ratings note", 107,
                  "Indexed Outer Sunset plumber page shows Legend Plumbing & Drain at 5.0 across about 20 reviews in a sponsored slot; never blended with other platforms.",
                  "Legend Plumbing & Drain 5.0 (20 reviews) Verified License (sponsored)"),
                 ("Coverage", 135,
                  "Business site lists San Francisco 94117 with 7 AM–8 PM hours seven days a week.",
                  "415-298-5181 · San Francisco 94117 · Monday–Sunday 7 AM – 8 PM")],
         website="https://legendplumbingsf.com/", websiteSource=135,
         phone="(415) 298-5181", phoneSource=135,
         flags=[{"level": "notice",
                 "text": "Site (415-298-5181) and Yelp profile (628-218-5447) display different phone numbers; confirm the current line when calling.",
                 "sources": [135, 140]}],
         gaps=["CSLB number not captured this pass.",
               "No exact seized-overflow extraction case verified.",
               "Sponsored placement is advertising, not merit evidence."]),
    dict(id="fa-plumbing", name="F&A Plumbing & Rooter", area="outside",
         areaText="Pacifica-based per its Yelp profile; San Francisco Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 111,
                  "Indexed San Francisco plumbing page lists F&A Plumbing&Rooter at 4.9 across about 150 reviews with a verified-license badge.",
                  "F&A Plumbing&Rooter 4.9 (150 reviews) Verified License · 20 years in business · Free estimates"),
                 ("Identity", 138,
                  "Yelp profile places F&A at 50 W Manor Dr Ste 1495, Pacifica, established 2012, listing drains, gas/water/sewer lines and fixtures.",
                  "50 W Manor Dr, Ste 1495, Pacifica, CA 94044 · (415) 728-5213 · Established in 2012"),
                 ("Corporate filing", 137,
                  "Third-party filing summary shows F&a Plumbing & Rooter incorporated in California on 01/12/2016 with active standing.",
                  "incorporated on January 12, 2016 · Status Active")],
         phone="(415) 728-5213", phoneSource=138,
         flags=[{"level": "gap",
                 "text": "Pacifica base; citywide SF and Outer Sunset dispatch not established by the evidence captured.",
                 "sources": [138]}],
         gaps=["No exact seized-overflow extraction case verified.",
               "CSLB number not captured this pass.",
               "Outer Sunset coverage unconfirmed."]),
    dict(id="portola", name="Portola Plumbing Services", area="sf",
         areaText="Serving San Francisco per the indexed plumbing page; dispatched coverage of the Outer Sunset unconfirmed.",
         claims=[("Discovery", 111,
                  "Indexed San Francisco plumbing page lists Portola Plumbing Services with bathtub installation, bathtub repair and drain installation service tags.",
                  "Portola Plumbing Services Serving San Francisco and the Surrounding Area · Bathtub installation Bathtub repair Drain installation · 10 mins response time · 312 locals recently requested a quote")],
         gaps=["No exact seized-overflow extraction case verified.",
               "No identity, address or license captured in this pass.",
               "Service tags do not prove seized trip-lever mechanism experience.",
               "Indexed sample may be stale."]),
    dict(id="phams", name="Pham's Plumbing", area="sf",
         areaText="Serving San Francisco per the indexed Outer Sunset plumber page; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 107,
                  "Indexed Outer Sunset plumber page lists Pham's Plumbing at 4.8 across about 22 reviews.",
                  "Pham's Plumbing 4.8 (22 reviews) Serving San Francisco and the Surrounding Area · 'the best, most exceptional, professional plumbing service'")],
         gaps=["No exact seized-overflow extraction case verified.",
               "No identity or license captured in this pass.",
               "Small review sample (about 22)."]),
    dict(id="marcos", name="Marco's Plumbing", area="sunset",
         areaText="Appears on the indexed Outer Sunset plumbing page; business base and coverage not independently confirmed.",
         claims=[("Discovery", 110,
                  "Indexed Outer Sunset plumbing result lists Marco's Plumbing with about 16 reviews and a 'started in 2013' summary line.",
                  "Marco's Plumbing 16 Plumbing · 'Recommended' according to 7 users · Marco's Plumbing started in 2013, leading all services, residential and commercial")],
         flags=[{"level": "notice",
                 "text": "Name-collision risk: Thumbtack hosts a separate-sounding 'Marco's Plumbing and Cleaning'. Do not merge reviews or assume one entity until a website, license or phone links them.",
                 "sources": [110, 122]}],
         gaps=["No exact seized-overflow extraction case verified.",
               "No identity or license captured in this pass.",
               "Small review sample (16)."]),
    dict(id="xray", name="X-Ray Plumbing And Drain", area="sf",
         areaText="Serving San Francisco per the indexed 24-hour plumber page; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 108,
                  "Indexed 24-hour plumber page lists X-Ray Plumbing And Drain at 5.0 across 48 reviews, open 24 hours, offering commercial services.",
                  "X-Ray Plumbing And Drain 5.0 (48 reviews) Serving San Francisco and the Surrounding Area · Open 24 hours · 'Excellent service!'")],
         gaps=["No exact seized-overflow extraction case verified.",
               "No identity or license captured in this pass.",
               "Sponsored placement is advertising, not merit evidence."]),
    dict(id="asap", name="ASAP Plumbing Pros", area="outside",
         areaText="Indexed as serving South San Francisco; SF Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 108,
                  "Indexed 24-hour plumber page shows ASAP Plumbing Pros at 4.8 across about 119 reviews with emergency services.",
                  "ASAP Plumbing Pros 4.8 (119 reviews) Serving South San Francisco and the Surrounding Area · Emergency services · On-time commitment"),
                 ("Thumbtack", 123,
                  "Thumbtack South San Francisco index lists ASAP Plumbing Pros as a Top Pro at 5.0 across about 325 reviews.",
                  "ASAP Plumbing Pros Top Pro Exceptional 5.0 (325) · Plumbing Pipe Repair, Plumbing Drain Repair, Sink or Faucet Repair, Toilet Repair"),
                 ("Thumbtack", 122,
                  "ASAP also appears in the San Francisco Thumbtack affordable-plumbing index with named customer quotes referencing technician Donald.",
                  "Jean C. 'Donald was quick to respond, punctual, and professional.'")],
         reviewIds=["R41"],
         gaps=["No exact seized-overflow extraction case verified.",
               "License not independently verified (badge and Top Pro tags are platform programs).",
               "Outer Sunset coverage unconfirmed from the South San Francisco base."]),
    dict(id="maverick", name="Maverick Water Heaters", area="unknown",
         areaText="Appears on the indexed Outer Sunset 24-hour plumber page; coverage beyond that not established.",
         claims=[("Discovery", 108,
                  "Indexed 24-hour plumber page lists Maverick Water Heaters at 5.0 across 31 reviews.",
                  "Maverick Water Heaters 5.0 (31 reviews) · free estimates")],
         gaps=["No exact seized-overflow extraction case verified.",
               "No identity or license captured in this pass.",
               "Name suggests a water-heater specialty; tub overflow scope unconfirmed."]),
    dict(id="wizard", name="Wizard Plumbing & Drain", area="sf",
         areaText="Listed among best San Francisco plumbers by a Yahoo Local editorial list; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 128,
                  "Yahoo Local's March 2026 editorial names Wizard Plumbing & Drain the best San Francisco plumber for same-day service, noting an EJ Home Services partnership.",
                  "Wizard Plumbing and Drain provides same-day service and durable repairs, now backed by a partnership with EJ Home Services… 'Ignacio was fantastic… got rid of a really hard sewer line clog.'")],
         flags=[{"level": "gap",
                 "text": "Source is a marketing-oriented listicle with affiliate-style placement; corroborate with license and review platforms before relying.",
                 "sources": [128]}],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "Editorial list placement is not cross-checked customer evidence."]),
    dict(id="economy", name="Economy Plumbing", area="sf",
         areaText="Business states 'We serve Daly City, Mission area and San Francisco.' Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 126,
                  "A Reddit commenter recommends Economy Plumbing for emergency and remodel-type work and posts its phone numbers and site.",
                  "'Economy Plumbing has come through for me EVERY TIME during the last 3 years!… never charged a trip charge… experienced with remodel type work… 415-337-7070 · https://economysf.com/services/'"),
                 ("Coverage", 139,
                  "Direct read of the business site states service to Daly City, the Mission area and San Francisco, 24/7, with a live September 2026 booking calendar.",
                  "We serve Daly City, Mission area and San Francisco. · 24/7 Plumber Service")],
         website="https://economysf.com/", websiteSource=139,
         phone="(415) 337-7070", phoneSource=126,
         reviewIds=["R42"],
         gaps=["No exact seized-overflow extraction case verified.",
               "CSLB record not yet located; 'licensed plumbers' wording is a business claim from its own site.",
               "Reddit recommendation is a single unverified account."]),
    dict(id="integrity-first", name="Integrity First Plumbing", area="sf",
         areaText="San Francisco mailing address (94124, Bayshore) on the CSLB record; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 126,
                  "A Reddit self-described licensed plumber's comparison table lists Integrity First Plumbing with CSLB #1006178 and cites remodels/new construction strengths.",
                  "Integrity First Plumbing | 1006178 | Remodels, new construction, resi service | ~4.8–5.0★"),
                 ("License", 104,
                  "Direct CSLB read: INTEGRITY FIRST PLUMBING INC, 1485 Bayshore Blvd 457, San Francisco 94124 — current and active C-36, expires 08/31/2027.",
                  "This license is current and active. · C36 - PLUMBING")],
         license={"number": "1006178", "status": "active", "entity": "INTEGRITY FIRST PLUMBING INC",
                  "expires": "2027-08-31", "classes": ["C36"], "source": 104, "checkedAt": RESEARCHED},
         phone="(415) 724-1100", phoneSource=104,
         flags=[{"level": "notice",
                 "text": "Discovered through a self-promotional Reddit comparison (poster is a plumber), not customer evidence; the CSLB record itself was independently read and matches.",
                 "sources": [126, 104]}],
         gaps=["No exact seized-overflow extraction case verified.",
               "No independent review corpus captured this pass.",
               "Outer Sunset dispatch unconfirmed; CSLB shows a 94124 mailing address."]),
    dict(id="repipe-champions", name="Repipe Champions", area="outside",
         areaText="Markets South San Francisco and the North Peninsula; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 133,
                  "Repipe Champions' South San Francisco page markets whole-house galvanized/PEX repipes with a printed 'CSLB #1057927' and a 4.9 Google rating claim.",
                  "Whole-House Repiping · South San Francisco, CA · CSLB #1057927 · 4.9★ Google Rating · 30-Year Warranty"),
                 ("Registry cross-check", 105,
                  "Direct CSLB read resolves #1057927 to ORTEGA'S BAY AREA GENERAL CONSTRUCTION INC of Hayward — an active B General Building license, not a C-36 plumbing license under the Repipe Champions name.",
                  "ORTEGA'S BAY AREA GENERAL CONSTRUCTION INC · 22352 MEEKLAND AVE · HAYWARD · B - GENERAL BUILDING · This license is current and active.")],
         flags=[{"level": "hold",
                 "text": "Identity mismatch: the license number printed on repipechampions.com (#1057927) belongs to a differently named Hayward general-building ('B') entity — not a C-36 plumbing license and not the marketing name. The exact contracting entity and its trade scope must be established before any plumbing engagement; a B license does not by itself authorize plumbing as a specialty trade.",
                 "sources": [133, 105]},
                {"level": "gap",
                 "text": "Repipe-only marketing conflicts with the repair-first objective (whole-house repipe is the last-resort path, not the first).",
                 "sources": [133]}],
         gaps=["No C-36 plumbing license under the marketing name found this pass.",
               "Outer Sunset coverage unconfirmed (South SF / North Peninsula focus).",
               "Hosted ratings claim (4.9 Google) is not an independent review corpus."]),
    dict(id="repipe-specialists", name="Repipe Specialists (San Francisco)", area="sf",
         areaText="San Francisco-dedicated marketing domain; actual dispatch footprint and local entity unconfirmed.",
         claims=[("Discovery", 134,
                  "Repipe Specialists' San Francisco local-services page markets galvanized pipe replacement, slab-leak reroutes and lifetime-warranty repipes.",
                  "Galvanized pipes installed in homes throughout San Francisco before the 1980s are now severely corroded… Our specialist teams will replace your aging pipes with modern PEX or copper systems · 'Saved me thousands of dollars by not requiring I remove the shower walls.'")],
         reviewIds=["R56"],
         flags=[{"level": "gap",
                 "text": "Franchise marketing page; local contracting entity and CSLB record not captured. Testimonials are company-hosted and not independent reviews.",
                 "sources": [134]}],
         gaps=["No exact seized-overflow extraction case verified.",
               "Local license entity unverified.",
               "Repipe-first marketing can bias toward replacement over preservation."]),
    dict(id="sf-plumbing-repairs", name="San Francisco Plumbing Repairs", area="outer",
         areaText="Yellow Pages listing places it at 645 Judah St, San Francisco 94122 (Inner Sunset edge) — same ZIP as the Outer Sunset.",
         claims=[("Discovery", 129,
                  "Yellow Pages San Francisco list shows San Francisco Plumbing Repairs at 645 Judah St, 94122, (415) 570-8420.",
                  "San Francisco Plumbing Repairs · Plumbers · (415) 570-8420 · 645 Judah St · San Francisco, CA 94122")],
         phone="(415) 570-8420", phoneSource=129,
         flags=[{"level": "notice",
                 "text": "Generic service-brand naming pattern (compare 'San Francisco Residential Plumbing' and 'San Francisco Find A Plumbing' from wave 3) is typical of directory lead-generation storefronts; obtain the legal entity and license before relying on it.",
                 "sources": [129]}],
         gaps=["No exact seized-overflow extraction case verified.",
               "Legal entity, license and real shop presence unverified.",
               "No independent reviews found under this exact name in this pass."]),
    dict(id="gateway-rooter", name="Gateway Rooter & Plumbing Inc", area="unknown",
         areaText="Listed on Yellow Pages San Francisco plumber pages without a shown street address; coverage unconfirmed.",
         claims=[("Discovery", 129,
                  "Yellow Pages San Francisco list names Gateway Rooter & Plumbing Inc among local plumbers.",
                  "Gateway Rooter & Plumbing Inc. - Plumbers"),
                 ("Second listing", 130,
                  "The Yellow Pages Central San Francisco list repeats Gateway Rooter & Plumbing Inc, again without an address in the indexed text.",
                  "Gateway Rooter & Plumbing Inc. - Plumbers")],
         gaps=["No exact seized-overflow extraction case verified.",
               "No address, license or review sample captured.",
               "Directory presence may be historical."]),
    # ---------------- Thumbtack plumbing discoveries ----------------
    dict(id="antonio-plumbing", name="Plumbing & Rooter Service (Antonio Cárcamo Reyes)", area="sf",
         areaText="Thumbtack profile states 'Serves San Francisco, CA' with 745 hires on the platform.",
         claims=[("Discovery", 124,
                  "Thumbtack 24-hour plumbers page lists Plumbing & Rooter Service (Antonio Cárcamo Reyes) as a Top Pro with 745 hires, serving San Francisco.",
                  "Plumbing & Rooter Service (Antonio Cárcamo Reyes) Top Pro Excellent 4.9 (314) · 745 hires on Thumbtack · Serves San Francisco, CA"),
                 ("Ratings note", 122,
                  "Thumbtack's San Francisco affordable-plumbing page shows the same profile at 4.9 across about 295 reviews.",
                  "Plumbing & Rooter Service (Antonio Cárcamo Reyes) Top Pro Excellent 4.9 (295)"),
                 ("Review sample", 125,
                  "Thumbtack JSON-LD carries a customer review praising professional integrity after a misdiagnosis was refunded.",
                  "'…he promptly refunded the test fee. I am both touched and impressed with his professional integrity…' — Sohela S.")],
         reviewIds=["R40"],
         gaps=["No exact seized-overflow extraction case verified.",
               "CSLB record not captured; Thumbtack 'Top Pro' is a platform tier, not a license.",
               "Sole-operator profile; confirm insurance and workers-comp status directly."]),
    dict(id="navta", name="Navta plumbing", area="sf",
         areaText="Appears in the Thumbtack San Francisco affordable-plumbing index; coverage beyond that unconfirmed.",
         claims=[("Discovery", 122,
                  "Thumbtack's San Francisco affordable-plumbing page lists Navta plumbing among its top-10 entries.",
                  "8. Navta plumbing")],
         gaps=["No exact seized-overflow extraction case verified.",
               "Profile-level detail (rating, hires, license) not captured in the extract.",
               "Coverage unconfirmed."]),
    dict(id="maximus", name="Maximus Plumbing & Heating", area="sf",
         areaText="Reviewed in the Thumbtack San Francisco index; business base not captured.",
         claims=[("Discovery", 122,
                  "Thumbtack San Francisco pages carry multiple customer endorsements for Maximus Plumbing & Heating, including rescue of an incomplete prior plumbing job.",
                  "'I reached out to Maximus Plumbing after a bad experience with a contractor who left us with an incomplete plumbing job… quick to respond, professional, and accommodating.'")],
         reviewIds=["R43"],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "Heating scope suggests HVAC mix; plumbing depth unconfirmed."]),
    dict(id="ayalas", name="Ayala's Plumbing Solutions", area="sf",
         areaText="Reviewed in the Thumbtack San Francisco affordable-plumbing index; base unconfirmed.",
         claims=[("Discovery", 122,
                  "Thumbtack San Francisco page carries a named customer endorsement for Ayala's Plumbing Solutions (technician Filberto).",
                  "'Filberto is very proficient in plumbing, his quality of work is excellent. I would recommend him highly.' — Harvey Q.")],
         reviewIds=["R44"],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "Outer Sunset coverage unconfirmed."]),
    dict(id="bright-ideas", name="Bright Ideas Plumbing and Rooter", area="sf",
         areaText="Reviewed in the Thumbtack San Francisco index; base unconfirmed.",
         claims=[("Discovery", 122,
                  "Thumbtack San Francisco page carries a named customer endorsement for Bright Ideas Plumbing and Rooter (technician Ronnie).",
                  "'Ronnie works with integrity and the utmost professionalism. I highly recommend him for your plumbing work!' — Alan E.")],
         reviewIds=["R45"],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "Outer Sunset coverage unconfirmed."]),
    dict(id="dr-drain", name="Dr. Drain Plumbing and Rooter", area="outside",
         areaText="Reviewed in the Thumbtack South San Francisco index; SF Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 123,
                  "Thumbtack South San Francisco page carries a customer review for Dr. Drain Plumbing and Rooter praising response and cleanup.",
                  "'Super fast response. Plumber was polite and arrived as scheduled. Got the job done and cleaned up the area properly.' — Erin L.")],
         reviewIds=["R46"],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "South San Francisco indexing; Outer Sunset coverage unconfirmed."]),
    dict(id="lgm", name="LGM Plumbing & Rooter", area="outside",
         areaText="Reviewed in the Thumbtack South San Francisco index; SF Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 123,
                  "Thumbtack South San Francisco page carries a detailed customer endorsement of technician Luis at LGM Plumbing & Rooter.",
                  "'Luis is the best plumber in the Bay Area… reasonable price and he uses quality materials — NO SHORT CUTS.' — Lester L.")],
         reviewIds=["R47"],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "Outer Sunset coverage unconfirmed."]),
    dict(id="route-to-problem", name="The Route To Your Problem", area="outside",
         areaText="Thumbtack South San Francisco index, 4.9 across 66 reviews; SF Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 123,
                  "Thumbtack South San Francisco page lists The Route To Your Problem as a Top Pro at 4.9 across 66 reviews.",
                  "The Route To Your Problem Top Pro Excellent 4.9 (66)")],
         reviewIds=["R48"],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "Outer Sunset coverage unconfirmed."]),
    dict(id="alpha-plumbing", name="Alpha Plumbing Solutions Llc", area="outside",
         areaText="Thumbtack South San Francisco index, 4.8 across 10 reviews; SF Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 123,
                  "Thumbtack South San Francisco page lists Alpha Plumbing Solutions Llc as a Top Pro at 4.8 across 10 reviews.",
                  "Alpha Plumbing Solutions Llc Top Pro Great 4.8 (10)")],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "Small review sample (10).",
               "Outer Sunset coverage unconfirmed."]),
    dict(id="doms", name="Dom's plumbing", area="outside",
         areaText="Thumbtack South San Francisco index, 5.0 across 7 reviews; SF Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 123,
                  "Thumbtack South San Francisco page lists Dom's plumbing at 5.0 across 7 reviews.",
                  "Dom's plumbing Exceptional 5.0 (7)")],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "Very small review sample (7).",
               "Outer Sunset coverage unconfirmed."]),
    dict(id="costellos", name="Costello's Plumbing", area="sf",
         areaText="Appears with a JSON-LD aggregate rating on the Thumbtack San Francisco plumbing page; base unconfirmed.",
         claims=[("Discovery", 125,
                  "Thumbtack San Francisco plumbing page JSON-LD rates Costello's Plumbing at 4.80 across 177 reviews.",
                  "{\"name\":\"Costello's Plumbing\",\"aggregateRating\":{\"ratingValue\":4.80,\"reviewCount\":177}}")],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "No individual review text captured for line-by-line reading.",
               "Outer Sunset coverage unconfirmed."]),
    dict(id="jn-son", name="JN and Son Plumbing", area="sf",
         areaText="Reviewed in the Thumbtack San Francisco plumbing index; base unconfirmed.",
         claims=[("Discovery", 125,
                  "Thumbtack San Francisco page carries customer mentions of JN and Son Plumbing.",
                  "'JN and Son Plumbing was great. Very friendly and on time.' — Jackie C.")],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "Indexed extract attribution requires profile confirmation.",
               "Outer Sunset coverage unconfirmed."]),
    dict(id="plumbing-bay-area", name="Plumbing Bay Area", area="sf",
         areaText="Thumbtack profile states 'Serves San Francisco, CA' with 16 hires.",
         claims=[("Discovery", 124,
                  "Thumbtack 24-hour plumbers page lists Plumbing Bay Area at 4.8 across 18 reviews with 16 hires, serving San Francisco.",
                  "Plumbing Bay Area Great 4.8 (18) · 16 hires on Thumbtack · Serves San Francisco, CA · 'Santwan promptly came out the same day and had me back up and running in an hour or less. No fuss and no mess.' — Kanchan G.")],
         reviewIds=["R50"],
         flags=[{"level": "notice",
                 "text": "Generic name sits one word apart from the established 'Bay Area Plumbing' already tracked in this research — do not merge their reviews or assume one company.",
                 "sources": [124]}],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "Small review sample (18)."]),
    dict(id="natan", name="Natan plumbing", area="sf",
         areaText="Thumbtack profile states 'Serves San Francisco, CA'; 3 hires on platform.",
         claims=[("Discovery", 124,
                  "Thumbtack 24-hour plumbers page lists Natan plumbing at 5.0 across 13 reviews, serving San Francisco.",
                  "Natan plumbing Exceptional 5.0 (13) · 3 hires on Thumbtack · Serves San Francisco, CA · 'I highly recommend Nathan to anyone looking for a reliable plumber!' — Aleksei S.")],
         reviewIds=["R49"],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "Small review sample (13) and tiny hire count (3)."]),
    dict(id="urban-bay", name="Urban Bay Engineering", area="sf",
         areaText="Sponsored drain-repair listing indexed as serving San Francisco; coverage specifics unconfirmed.",
         claims=[("Discovery", 112,
                  "Indexed San Francisco drain-cleaning page shows a sponsored Urban Bay Engineering listing under the drain-repair tag.",
                  "Urban Bay Engineering Serving San Francisco and the Surrounding Area · Free estimates · Locally owned & operated · Drain repair")],
         flags=[{"level": "gap",
                 "text": "'Engineering' in the business name with a drain-repair tag is an unusual pairing; the legal entity, trade classification and scope need direct confirmation before any engagement.",
                 "sources": [112]}],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license, reviews or address captured.",
               "Sponsored placement is advertising, not merit evidence."]),
    dict(id="absolute-sanitation", name="Absolute Sanitation Plumbing and Restoration", area="unknown",
         areaText="Appears on an indexed San Francisco water-ceiling-leak page; base and coverage unconfirmed.",
         claims=[("Discovery", 121,
                  "Indexed San Francisco water-ceiling-leak page lists Absolute Sanitation Plumbing and Restoration at 4.8 across 53 reviews.",
                  "Absolute Sanitation Plumbing and Restoration 4.8 (53 reviews)")],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured in this pass.",
               "Combined plumbing + restoration scope could fit tub-leak-into-ceiling cases, but nothing is verified."]),
    # ---------------- Drywall / paint / remodel discoveries ----------------
    dict(id="a1-drywall", name="A1 Drywall", area="sf",
         areaText="Indexed as serving San Francisco on the drywall-contractor page; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 113,
                  "Indexed San Francisco drywall-contractor page lists A1 Drywall at 4.7 across 68 reviews with a ceiling/wall-opening repair quote.",
                  "A1 Drywall 4.7 (68 reviews) Serving San Francisco and the Surrounding Area · 'opening up the ceiling and walls, we needed a professional drywall contractor that could replace…'")],
         reviewIds=["R55"],
         flags=[{"level": "notice",
                 "text": "A different indexed drywall page shows a review excerpt under A1 Drywall's slot praising 'Genuine Drywall' — possible index cross-brand bleed; verify the exact profile and sample when reading reviews.",
                 "sources": [113]}],
         gaps=["No exact seized-overflow extraction case verified.",
               "License class/status unchecked.",
               "Drywall scope — ceiling-open and restore phase only, not plumbing."]),
    dict(id="paint-studio", name="Paint Studio SF", area="sf",
         areaText="Indexed as serving San Francisco on the drywall-contractor page; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 113,
                  "Indexed San Francisco drywall-contractor page lists Paint Studio SF at 4.6 across 71 reviews.",
                  "Paint Studio SF 4.6 (71 reviews) Serving San Francisco and the Surrounding Area")],
         gaps=["No exact seized-overflow extraction case verified.",
               "License class/status unchecked.",
               "Paint-led scope; hatch closure and texture match only."]),
    dict(id="benjamin-shaw", name="Benjamin Shaw", area="sf",
         areaText="Indexed as serving San Francisco on the drywall-contractor page; business base and trade scope unconfirmed.",
         claims=[("Discovery", 113,
                  "Indexed San Francisco drywall-contractor page lists Benjamin Shaw at 4.9 across 32 reviews.",
                  "Benjamin Shaw 4.9 (32 reviews) Serving San Francisco and the Surrounding Area")],
         gaps=["No exact seized-overflow extraction case verified.",
               "Trade scope (drywall vs painting vs general) not established in the extract.",
               "License unchecked."]),
    dict(id="carlos-painting", name="Carlos' Painting & Handyman", area="sf",
         areaText="Indexed as serving San Francisco on the drywall repair-and-paint page; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 114,
                  "Indexed San Francisco drywall repair-and-paint page lists Carlos' Painting & Handyman at 4.9 across 123 reviews.",
                  "Carlos' Painting & Handyman 4.9 (123 reviews) Serving San Francisco and the Surrounding Area")],
         gaps=["No exact seized-overflow extraction case verified.",
               "License unchecked; handyman naming may cap job value for plumbing tasks.",
               "Drywall patch/finish phase only."]),
    dict(id="northwest-builders", name="Northwest Builders & Renovation", area="unknown",
         areaText="Appears on the indexed San Francisco drywall-contractor page; base unconfirmed.",
         claims=[("Discovery", 113,
                  "Indexed San Francisco drywall-contractor page shows Northwest Builders & Renovation at 3.3 across 8 reviews in a promoted slot.",
                  "Northwest Builders & Renovation 3.3 (8 reviews)")],
         flags=[{"level": "notice",
                 "text": "Low indexed star sample (3.3★ across ~8 reviews); investigate the cause before shortlisting.",
                 "sources": [113]}],
         gaps=["No exact seized-overflow extraction case verified.",
               "No license or address captured.",
               "Low review rating and tiny sample."]),
    dict(id="fullhouse", name="Fullhouse Remodeling & Handyman Services", area="sf",
         areaText="Indexed as serving San Francisco on the handyman page; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 117,
                  "Indexed San Francisco handyman page lists Fullhouse Remodeling & Handyman Services at 4.8 across about 20 reviews with a bathroom-vanity project photo.",
                  "Fullhouse Remodeling & Handyman Services 4.8 (20 reviews) Serving San Francisco and the Surrounding Area · Certified professionals")],
         gaps=["No exact seized-overflow extraction case verified.",
               "License unchecked.",
               "Remodel/handyman scope — hatch carpentry and finish, not plumbing."]),
    # ---------------- Handyman discoveries ----------------
    dict(id="sunset-handyman", name="Sunset Handyman", area="sunset",
         areaText="'Sunset'-branded San Francisco handyman; listed service includes San Francisco — Outer Sunset dispatch unconfirmed beyond the name.",
         claims=[("Discovery", 115,
                  "Indexed Yelp profile for Sunset Handyman shows 5.0 across 4 reviews; the owner describes 15+ years of framing/finish carpentry and small-project availability.",
                  "Sunset Handyman 5.0 (4 reviews) · Local framing and finish carpenter with over 15 years experience… Currently taking small scale projects and handyman jobs · 650-430-8565")],
         phone="(650) 430-8565", phoneSource=115,
         reviewIds=["R53"],
         gaps=["No plumbing scope — carpentry/hatch phase only.",
               "License unchecked (handyman work in CA is limited in value without a license).",
               "Tiny review sample (4)."]),
    dict(id="handyman-heroes", name="Handyman Heroes", area="sf",
         areaText="Indexed as serving San Francisco on the Outer Sunset handyman page; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 116,
                  "Indexed Outer Sunset handyman page lists Handyman Heroes at 4.7 across 398 reviews, certified professionals, locally owned.",
                  "Handyman Heroes 4.7 (398 reviews) Serving San Francisco and the Surrounding Area · Certified professionals · Locally owned & operated"),
                 ("Scope note", 117,
                  "A customer excerpt states the household employed Handyman Heroes for both handyman and plumbing services.",
                  "'We have employed Handyman Heroes for both their handyman services and plumbing services.'")],
         reviewIds=["R54"],
         gaps=["No exact seized-overflow extraction case verified.",
               "License class unchecked — plumbing work above small-job thresholds needs a C-36.",
               "Franchise-style dispatch; individual technician skill varies."]),
    dict(id="honest-mikes", name="Reasonably Honest Mike's", area="sf",
         areaText="Indexed as serving San Francisco on the handyman page; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 116,
                  "Indexed Outer Sunset handyman page lists Reasonably Honest Mike's at 4.9 across 90 reviews.",
                  "Reasonably Honest Mike's 4.9 (90 reviews) · 'Mike is your one stop reliable handyman. We needed a dimmer switch fixed on some old wiring.'")],
         gaps=["No plumbing scope evidence in the extract.",
               "License unchecked.",
               "Handyman scope — hatch/finish phase only."]),
    dict(id="handlify", name="Handlify", area="sf",
         areaText="Indexed as serving San Francisco on the handyman page; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 117,
                  "Indexed San Francisco handyman page lists Handlify at 4.9 across 151 reviews with disposal-replacement and wall-recovery photos.",
                  "Handlify 4.9 (151 reviews) Serving San Francisco and the Surrounding Area · 'dependable handyman who can handle a wide variety of repairs' · After: brand new disposal, recovered wall")],
         gaps=["No exact seized-overflow extraction case verified.",
               "License unchecked.",
               "App-dispatch model; technician identity varies."]),
    dict(id="paul-woodford", name="Paul Woodford Services", area="sf",
         areaText="Indexed as serving San Francisco on the handyman page; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 117,
                  "Indexed San Francisco handyman page lists Paul Woodford Services at 4.7 across 83 reviews with bathroom tiling portfolio photos.",
                  "Paul Woodford Services 4.7 (83 reviews) Serving San Francisco and the Surrounding Area · 'This is an excellent company… check out their website' · Bathroom tiling complete")],
         gaps=["No exact seized-overflow extraction case verified.",
               "License unchecked.",
               "Handyman scope — hatch/finish phase only."]),
    dict(id="octavio", name="Octavio Handyman", area="sf",
         areaText="Indexed as serving San Francisco on the Outer Sunset handyman page; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 116,
                  "Indexed Outer Sunset handyman page lists Octavio Handyman at 5.0 across 6 reviews with wall repair and repaint excerpts.",
                  "Octavio Handyman 5.0 (6 reviews) · 'We needed a wall repaired and repainted. He gave a fair estimate.' · 'I needed help with a plumbing job ASAP and he was super responsive…'")],
         gaps=["No exact seized-overflow extraction case verified.",
               "License unchecked; very small review sample (6).",
               "Mixed wall/plumbing excerpts at handyman value caps."]),
    dict(id="sf-handyman-services", name="San Francisco Handyman Services", area="sf",
         areaText="San Francisco handyman business; Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 118,
                  "Indexed Yelp profile for San Francisco Handyman Services shows 5.0 across 3 reviews; services include drywall installation and repair.",
                  "San Francisco Handyman Services 5.0 (3 reviews) · family-owned business with over 40 years of experience · drywall installation and repair")],
         gaps=["No plumbing scope evidence.",
               "License unchecked.",
               "Very small review sample (3)."]),
    # ---------------- Water damage / restoration discoveries ----------------
    dict(id="mikes-water-damage", name="Mike's Water Damage", area="sf",
         areaText="San Francisco (94107) per its Yelp profile with 24/7 posting; dispatches across SF per review locations.",
         claims=[("Discovery", 119,
                  "Indexed Yelp profile for Mike's Water Damage shows 4.9 across 72 reviews with detailed SF ceiling water-damage mitigation accounts.",
                  "Mike's Water Damage 4.9 (72 reviews) · Open 24 hours · aggregateRating 4.9 · (650) 514-1414 · San Francisco, CA 94107"),
                 ("Drywall scope", 120,
                  "A second indexed San Francisco page carries a quote praising drywall repair after water damage by the same listed business.",
                  "'Great job repairing drywall after some water damage. Team was responsive.'")],
         phone="(650) 514-1414", phoneSource=119,
         reviewIds=["R51", "R52"],
         gaps=["No plumbing scope — mitigation/dryout and drywall only.",
               "License unchecked.",
               "Does not perform the overflow mechanism repair itself."]),
    dict(id="dry-kings", name="Dry Kings Restoration", area="sf",
         areaText="420 Berry St, Mission Bay, San Francisco per the indexed page; coverage across SF plausible but unconfirmed.",
         claims=[("Discovery", 121,
                  "Indexed San Francisco water-ceiling-leak page lists Dry Kings Restoration at 4.8 across 122 reviews at 420 Berry St with a verified-license badge and 24/7 availability.",
                  "Dry Kings Restoration 4.8 (122 reviews) 420 Berry St Mission Bay · Verified License · Emergency services · 24/7 Availability")],
         gaps=["No plumbing scope — mitigation/dryout only.",
               "License number not captured (badge is a platform signal).",
               "Does not perform the overflow mechanism repair itself."]),
    dict(id="all-action", name="All Action Water Damage", area="outside",
         areaText="Burlingame-based per the indexed page; SF dispatch unconfirmed.",
         claims=[("Discovery", 120,
                  "Indexed San Francisco ceiling-leak page lists All Action Water Damage at 4.9 across 126 reviews with a verified-license badge and 22 years in business.",
                  "All Action Water Damage 4.9 (126 reviews) Serving Burlingame and the Surrounding Area · Verified License · 22 years in business · On their website: leak repair"),
                 ("Relevant quote", 121,
                  "An indexed excerpt within All Action's listing describes a flooded upstairs bathroom leaking through drywall — structurally similar to the target scenario.",
                  "'My husband and I woke up this week to a flooded upstairs bathroom and water leaking through our drywall…'")],
         reviewIds=["R57"],
         gaps=["No plumbing scope — mitigation/dryout only.",
               "Burlingame base; Outer Sunset dispatch unconfirmed.",
               "License number not captured."]),
    dict(id="safenest", name="SAFENEST Restoration", area="sf",
         areaText="Indexed as serving San Francisco on the water-ceiling-leak page; dispatch specifics unconfirmed.",
         claims=[("Discovery", 121,
                  "Indexed San Francisco water-ceiling-leak page lists SAFENEST Restoration at 4.9 across 78 reviews, 10 years in business.",
                  "SAFENEST Restoration 4.9 (78 reviews) Serving San Francisco and the Surrounding Area · 10 years in business")],
         flags=[{"level": "notice",
                 "text": "An excerpt indexed inside SAFENEST's listing praises 'Mike's Water Damage (aka Water's Fault)' — cross-listing text bleed in the index; do not blend the two businesses' ratings or reviews.",
                 "sources": [121]}],
         gaps=["No plumbing scope — mitigation/dryout only.",
               "License unchecked.",
               "Index text-bleed noted; read its profile directly if shortlisted."]),
    dict(id="max-restoration", name="Max Restoration", area="outside",
         areaText="South San Francisco per the indexed page; SF Outer Sunset dispatch unconfirmed.",
         claims=[("Discovery", 121,
                  "Indexed San Francisco water-ceiling-leak page lists Max Restoration at 5.0 across 32 reviews, family-owned.",
                  "Max Restoration 5.0 (32 reviews) Serving South San Francisco and the Surrounding Area · 'Dio did a great job remediating the black mold and water damage caused by my washer.'")],
         reviewIds=["R58"],
         gaps=["No plumbing scope — mitigation/dryout only.",
               "License unchecked.",
               "Outer Sunset coverage unconfirmed."]),
]


def build(row):
    b = {
        "id": row["id"],
        "name": row["name"],
        "website": row.get("website"),
        "websiteSource": row.get("websiteSource"),
        "status": "research",
        "area": row["area"],
        "areaText": row["areaText"],
        "license": row.get("license"),
        "phone": row.get("phone"),
        "phoneSource": row.get("phoneSource"),
        "claims": [
            {"field": field, "text": text, "source": source, "excerpt": excerpt}
            for field, source, text, excerpt in row["claims"]
        ],
        "flags": row.get("flags", []),
        "reviewIds": row.get("reviewIds", []),
        "exactMatch": False,
        "master": False,
        "checkedAt": RESEARCHED,
        "platformLinks": row.get("platformLinks", []),
        "gaps": row["gaps"],
    }
    assert b["claims"][0]["field"] == "Discovery", b["id"]
    assert len(b["gaps"]) >= 2, b["id"]
    return b


businesses = [build(r) for r in ROWS]
_ids = [b["id"] for b in businesses]
assert len(_ids) == len(set(_ids)) == 50, "wave 4 must hold exactly 50 unique businesses"

REVIEWS = [
    {"id": "R40", "business": "antonio-plumbing", "platform": "Thumbtack", "author": "Sohela S.",
     "published": "Not displayed",
     "quote": "The fellow who came over misdiagnosed the issue after running some tests and we paid for it… when I let Antonio know that they had the wrong diagnosis and proposed solution, he promptly refunded the test fee. I am both touched and impressed with his professional integrity…",
     "analysis": "Thumbtack JSON-LD review: a misdiagnosis was owned and refunded. Diagnostic honesty is a desirable trait for a seized-mechanism problem, but no tub work is described.",
     "theme": "Diagnostic options", "source": 125, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R41", "business": "asap", "platform": "Thumbtack", "author": "Jean C.",
     "published": "Not displayed",
     "quote": "Donald was quick to respond, punctual, and professional. I would hire again for any plumbing needs.",
     "analysis": "Indexed Thumbtack quote adjacent to ASAP Plumbing Pros (technician Donald); supports responsiveness only — no overflow or wall-related content.",
     "theme": "Reliability (dated)", "source": 122, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R42", "business": "economy", "platform": "Reddit", "author": "AppropriateLawyer518",
     "published": "Posted under a Nov 2025 thread per index",
     "quote": "Economy Plumbing has come through for me EVERY TIME during the last 3 years!… good to add for Emergency Calls and same day availability… they have never charged a trip charge. They have several guys that are experienced with remodel type work…",
     "analysis": "Single Reddit endorsement: emergency availability, no trip charge and remodel-type experience — useful signals, but one unverified account with no tub-specific job.",
     "theme": "Community recommendation", "source": 126, "access": "search-extract", "identity": "unverified-username",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R43", "business": "maximus", "platform": "Thumbtack", "author": "Rebekah W.",
     "published": "Not displayed",
     "quote": "I reached out to Maximus Plumbing after a bad experience with a contractor who left us with an incomplete plumbing job. This team was quick to respond, professional, and accommodating. Will definitely be using them again.",
     "analysis": "Indexed Thumbtack quote about rescuing an incomplete prior job — a recovery scenario, thematically close to difficult plumbing situations but not a seized overflow.",
     "theme": "Complex repair", "source": 122, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R44", "business": "ayalas", "platform": "Thumbtack", "author": "Harvey Q.",
     "published": "Not displayed",
     "quote": "Filberto is very proficient in plumbing, his quality of work is excellent. I would recommend him highly. I would hire him on any future plumbing jobs.",
     "analysis": "Indexed Thumbtack endorsement naming a specific technician (Filberto); general proficiency only, no task detail.",
     "theme": "General quality", "source": 122, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R45", "business": "bright-ideas", "platform": "Thumbtack", "author": "Alan E.",
     "published": "Not displayed",
     "quote": "Ronnie works with integrity and the utmost professionalism. I highly recommend him for your plumbing work!",
     "analysis": "Indexed Thumbtack endorsement naming technician Ronnie; integrity signal only, no task detail.",
     "theme": "General quality", "source": 122, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R46", "business": "dr-drain", "platform": "Thumbtack", "author": "Erin L.",
     "published": "Not displayed",
     "quote": "Super fast response. Plumber was polite and arrived as scheduled. Got the job done and cleaned up the area properly. Happy to use Dr. Drain Plumbing.",
     "analysis": "Indexed Thumbtack review from the South San Francisco page; cleanup care is relevant to work above an occupied unit, but no task detail.",
     "theme": "Clean work", "source": 123, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R47", "business": "lgm", "platform": "Thumbtack", "author": "Lester L.",
     "published": "Not displayed",
     "quote": "Luis is the best plumber in the Bay Area. I am very particular about quality, punctuality and responsiveness. He had it all! His price is reasonable and he uses quality materials — NO SHORT CUTS.",
     "analysis": "Indexed Thumbtack endorsement of a named technician (Luis); no-shortcuts quality claim from a self-described exacting customer, but no task detail.",
     "theme": "General quality", "source": 123, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R48", "business": "route-to-problem", "platform": "Thumbtack", "author": "Kim W.",
     "published": "Not displayed",
     "quote": "I had a leak in my kitchen sink (sadly, a repair I made last year with another plumbing company) and Manny did an excellent job removing faulty old pipes.",
     "analysis": "Indexed Thumbtack quote adjacent to this business's listing, describing removal of faulty old pipes — adjacent to aged-materials plumbing but attribution follows index adjacency and needs profile confirmation.",
     "theme": "Complex repair", "source": 123, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R49", "business": "natan", "platform": "Thumbtack", "author": "Aleksei S.",
     "published": "Not displayed",
     "quote": "I highly recommend Nathan to anyone looking for a reliable plumber!",
     "analysis": "Indexed Thumbtack endorsement; reliability signal only, no task detail. Tiny hire count (3) and review sample (13) limit confidence.",
     "theme": "General quality", "source": 124, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R50", "business": "plumbing-bay-area", "platform": "Thumbtack", "author": "Kanchan G.",
     "published": "Not displayed",
     "quote": "Santwan promptly came out the same day and had me back up and running in an hour or less. No fuss and no mess.",
     "analysis": "Indexed Thumbtack quote praising same-day response and tidiness; no task detail and the business name invites confusion with 'Bay Area Plumbing'.",
     "theme": "Reliability (dated)", "source": 124, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R51", "business": "mikes-water-damage", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed",
     "quote": "Great job repairing drywall after some water damage. Team was responsive.",
     "analysis": "Indexed Yelp quote under Mike's Water Damage on a San Francisco ceiling-leak page; directly relevant to the ceiling-restore phase after a leak.",
     "theme": "Drywall finishing", "source": 120, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R52", "business": "mikes-water-damage", "platform": "Yelp", "author": "Jackie Z.",
     "published": "Jan 16, 2026 per indexed extract",
     "quote": "As a Property Manager, I hired Mike's Water Damage to come out after my clients home in SF was flooded… I'm so grateful Mike answered my call at 10:30pm on a Sunday!",
     "analysis": "Indexed Yelp review by a property manager — the same stakeholder type as the target rental property; shows late-night response, no plumbing repair content.",
     "theme": "Water damage", "source": 119, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R53", "business": "sunset-handyman", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed",
     "quote": "Mark Lajoie is an excellent Handyman… neat and organized… asked questions about the mirror and materials I had prior to showing up so that he could be sure he had all he needed to accomplish the hanging timely and accurately…",
     "analysis": "Indexed Yelp review of a careful, prepared small-job handyman — the profile of tradesperson suited to access-hatch carpentry; no plumbing content.",
     "theme": "Finish work", "source": 115, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R54", "business": "handyman-heroes", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed",
     "quote": "We have employed Handyman Heroes for both their handyman services and plumbing services.",
     "analysis": "Indexed Yelp excerpt indicating one provider was used across handyman and plumbing categories — the combined scope this project needs; license class still unchecked.",
     "theme": "Multi-trade scope", "source": 117, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R55", "business": "a1-drywall", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed",
     "quote": "opening up the ceiling and walls, we needed a professional drywall contractor that could replace…",
     "analysis": "Indexed Yelp quote describing ceiling and wall opening with professional replacement — directly relevant to the ceiling-open and restore phase.",
     "theme": "Ceiling repair", "source": 113, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R56", "business": "repipe-specialists", "platform": "Business site", "author": "Company-hosted testimonial — name not displayed in extract",
     "published": "Not displayed",
     "quote": "Saved me thousands of dollars by not requiring I remove the shower walls.",
     "analysis": "Company-hosted testimonial on the repipe vendor's own SF page: preservation-friendly in spirit, but it is marketing content, not an independent review, and promotes repipes.",
     "theme": "Older-home experience", "source": 134, "access": "search-extract", "identity": "company-published",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R57", "business": "all-action", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed",
     "quote": "You guys don't need to look any further. My husband and I woke up this week to a flooded upstairs bathroom and water leaking through our drywall…",
     "analysis": "Indexed Yelp quote within All Action's listing describing exactly the tub-overflow consequence pattern — an upstairs bathroom leaking through the ceiling below; mitigation scope, not plumbing repair.",
     "theme": "Water damage", "source": 121, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R58", "business": "max-restoration", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed",
     "quote": "Dio did a great job remediating the black mold and water damage caused by my washer.",
     "analysis": "Indexed Yelp quote on appliance-leak remediation; analogous moisture scenario, no bathroom or plumbing content.",
     "theme": "Water damage", "source": 121, "access": "search-extract", "identity": "indexed",
     "negative": False, "checkedAt": RESEARCHED, "exactTask": False},
]

wave = {"wave": 4, "note": "50 new discovery records; 5 direct CSLB reads; nothing promoted.",
        "businesses": businesses, "sources": SOURCES, "reviews": REVIEWS}
out = ROOT / "data" / "wave4.json"
out.write_text(json.dumps(wave, indent=1, ensure_ascii=False) + "\n")
print(f"wrote {out}: {len(businesses)} businesses, {len(SOURCES)} sources, {len(REVIEWS)} reviews")
