#!/usr/bin/env python3
"""Generate data/wave3.json (discovery-level research pass, Sep 10 2026).

Every claim maps to a real source URL that was actually retrieved this pass
(Yelp / Yellow Pages / business-site indexed extracts). No license numbers,
phone numbers, or review quotes are invented: where a field is unverified it
is left null and recorded as an explicit gap. License/CSLB verification for
these leads is intentionally left as a follow-up pass (fail-closed by design).
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESEARCHED = "2026-09-10"

# New sources for this wave (existing dataset uses ids 1..90).
SOURCES = [
    {"id": 91, "title": "Yelp · Drywall Installation near Outer Sunset (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Drywall+Installation&find_loc=Outer+Sunset%2C+San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Direct Yelp access blocked; indexed search-page names, stars and quote fragments."},
    {"id": 92, "title": "Yelp · Drywall Repair in San Francisco (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=drywall+repair&find_loc=San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed search page; names, stars and quote fragments only."},
    {"id": 93, "title": "Yelp · Contractor near Outer Sunset (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Contractor&find_loc=Outer+Sunset%2C+San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed search page; names, stars and quote fragments only."},
    {"id": 94, "title": "Yelp · Bathroom Remodeling Contractor San Francisco (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Bathroom+Remodeling+Contractor&find_loc=San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed search page; names, stars and quote fragments only."},
    {"id": 95, "title": "Yelp · Water Damage Repair near Outer Sunset (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Water+Damage+Repair&find_loc=Outer+Sunset%2C+San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed search page; names, stars and quote fragments only."},
    {"id": 96, "title": "Yelp · Water Extraction near Outer Sunset (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Water+Extraction&find_loc=Outer+Sunset%2C+San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed search page; names, stars and quote fragments only."},
    {"id": 97, "title": "Yelp · Handyman near Outer Sunset (indexed extract)",
     "url": "https://www.yelp.com/search?find_desc=Handyman&find_loc=Outer+Sunset%2C+San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed search page; names, stars and quote fragments only."},
    {"id": 98, "title": "Yelp · Plumbing near Sunset District (indexed extract)",
     "url": "https://www.yelp.com/search?cflt=plumbing&find_loc=Sunset+District%2C+San+Francisco%2C+CA",
     "kind": "directory", "access": "blocked-with-search-extract", "checkedAt": RESEARCHED,
     "note": "Indexed search page; names, stars and quote fragments only."},
    {"id": 99, "title": "CertaPro Painters of San Francisco · Outer Sunset drywall",
     "url": "https://certapro.com/san-francisco/professional-painters-outer-sunset/",
     "kind": "business", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Business marketing page; lists Outer Sunset among service areas and offers drywall repair + EPA Lead Certified renovation."},
    {"id": 100, "title": "San Francisco Flood Repair · Water Damage in Outer Sunset",
     "url": "https://www.sanfranciscofloodrepair.com/water-damage-in-outer-sunset/",
     "kind": "business", "access": "search-extract", "checkedAt": RESEARCHED,
     "note": "Allied Restoration marketing page describing water-damage and ceiling/wall opening for dryout in SF."},
]

# Compact business rows:
# id, name, source_id, excerpt(real), area, areaText(real), discovery_text(real), extra_gaps[list]
# optional kwargs: phone, phoneSource, website, websiteSource, flags, reviewIds
ROWS = [
    # ---- Plumbing (cite existing verified Yelp/YP sources) ----
    ("gerber", "Gerber Plumbing", 70,
     "Gerber Plumbing 5.0 (2 reviews) Verified License",
     "outer", "Appears in the Outer Sunset plumbing index; coverage not independently confirmed.",
     "Indexed Yelp Outer Sunset result lists Gerber Plumbing with a verified-license badge.",
     ["No identity, license or address verified in this pass.", "Very small review sample (2)."]),
    ("bill-callaway", "Bill Callaway Plumber", 2,
     "{\"name\":\"Bill Callaway Plumber\",\"streetAddress\":\"3141 Balboa St\",\"postalCode\":\"94121\"}",
     "sf", "3141 Balboa St, San Francisco 94121 (Outer Richmond) per Yellow Pages listing.",
     "Yellow Pages Outer Sunset plumbers listing places Bill Callaway Plumber at 3141 Balboa St (Outer Richmond).",
     ["Outer Richmond address; Outer Sunset dispatch not confirmed.", "License unchecked."]),
    ("master-plumbing-sfg", "Master Plumbing SFG", 70,
     "Master Plumbing SFG · Bathtub repair · Drain repair",
     "unknown", "Appears on the indexed Outer Sunset plumbing results page; coverage beyond that not established.",
     "Indexed Yelp Outer Sunset result lists Master Plumbing SFG with bathtub-repair and drain-repair service tags.",
     ["No identity or license captured in this pass.", "Service tags do not prove seized-mechanism experience.", "Indexed sample may be stale."]),
    ("better-cost-backflow", "Better Cost Backflow Test & Service", 70,
     "Better Cost Backflow Test & Service · 19 reviews · Backflow Services",
     "unknown", "Appears on the indexed Outer Sunset plumbing results page; coverage beyond that not established.",
     "Indexed Yelp Outer Sunset result lists Better Cost Backflow Test & Service (backflow scope).",
     ["Backflow-only scope; not a tub/overflow repair fit.", "No identity or license captured.", "Outer Sunset coverage not confirmed."]),
    ("rooter-247", "24-7 Rooter & Plumbing", 70,
     "24-7 Rooter & Plumbing · Drain repair",
     "unknown", "Appears on the indexed Outer Sunset plumbing results page; coverage beyond that not established.",
     "Indexed Yelp Outer Sunset result lists 24-7 Rooter & Plumbing under drain-repair listings.",
     ["No identity or license captured.", "Drain focus; overflow-mechanism work unproven.", "Indexed sample may be stale."]),

    # ---- Drywall / finish ----
    ("amadors-drywall", "Amador's Drywall", 91,
     "Amador's Drywall 4.9 (64 reviews) Verified License",
     "sf", "Indexed Yelp drywall page; base appears South San Francisco per other listings.",
     "Indexed Yelp drywall-installation page lists Amador's Drywall at 4.9 across about 64 reviews.",
     ["SF Outer Sunset dispatch not confirmed (SSF base).", "License class/status unchecked.", "Drywall scope — patch/hatch phase only."]),
    ("rr-drywall", "R & R Drywall", 91,
     "R & R Drywall 4.8 (85 reviews)",
     "unknown", "Appears on the indexed Outer Sunset drywall results page; base not established.",
     "Indexed Yelp drywall-installation page lists R & R Drywall at 4.8 across about 85 reviews.",
     ["No identity or license captured.", "Drywall scope — patch/hatch phase only."]),
    ("ryno-drywall", "Ryno Drywall", 91,
     "Ryno Drywall 5.0 (14 reviews)",
     "unknown", "Appears on the indexed Outer Sunset drywall results page; base not established.",
     "Indexed Yelp drywall-installation page lists Ryno Drywall at 5.0 across about 14 reviews.",
     ["No identity or license captured.", "Small review sample.", "Drywall scope — patch/hatch phase only."]),
    ("baltodano", "Baltodano's Drywall & Painting", 91,
     "Baltodano's Drywall & Painting 4.4 (42 reviews)",
     "unknown", "Appears on the indexed Outer Sunset drywall results page; base not established.",
     "Indexed Yelp drywall-installation page lists Baltodano's Drywall & Painting at 4.4 across about 42 reviews.",
     ["No identity or license captured.", "Drywall scope — patch/hatch phase only."]),
    ("montes-drywall", "Montes Drywall Experts", 91,
     "Montes Drywall Experts 5.0 (12 reviews)",
     "unknown", "Appears on the indexed Outer Sunset drywall results page; base not established.",
     "Indexed Yelp drywall-installation page lists Montes Drywall Experts at 5.0 across about 12 reviews.",
     ["No identity or license captured.", "Small review sample.", "Drywall scope — patch/hatch phase only."]),
    ("toms-painters", "Toms Painters", 91,
     "Toms Painters 4.8 (240 reviews) · Drywall installation or replacement",
     "unknown", "Indexed Yelp drywall page; base not established for Outer Sunset dispatch.",
     "Indexed Yelp drywall page lists Toms Painters at 4.8 across about 240 reviews with drywall work.",
     ["No identity or license captured.", "Painting-led firm; confirm drywall/trade license.", "Drywall scope — finish phase only."]),
    ("dasilva-painting", "DaSilva Painting", 91,
     "DaSilva Painting 4.8 (145) · drywall, plaster type work & painting",
     "unknown", "Indexed Yelp drywall page; base not established for Outer Sunset dispatch.",
     "Indexed Yelp drywall page lists DaSilva Painting at 4.8 across about 145 reviews with drywall/plaster work.",
     ["No identity or license captured.", "Painting-led firm; confirm drywall/trade license.", "Drywall scope — finish phase only."]),
    ("all-around-builder", "All Around Builder", 91,
     "All Around Builder 5.0 (13) · drywall process",
     "unknown", "Appears on the indexed Outer Sunset drywall results page; base not established.",
     "Indexed Yelp drywall page lists All Around Builder at 5.0 across about 13 reviews describing a drywall process.",
     ["No identity or license captured.", "Small review sample.", "Confirm GC license class for finish phase."]),
    ("new-concept", "A New Concept General Construction", 91,
     "A New Concept General Construction 5.0 (13) · drywall repair",
     "unknown", "Appears on the indexed Outer Sunset drywall results page; base not established.",
     "Indexed Yelp drywall page lists A New Concept General Construction at 5.0 across about 13 reviews with drywall repair.",
     ["No identity or license captured.", "Small review sample.", "Confirm GC license class."]),
    ("crew-stucco", "The Crew Stucco & Plastering", 92,
     "The Crew Stucco & Plastering 4.3 (7) · drywall repair",
     "unknown", "Appears on the indexed San Francisco drywall-repair results page; base not established.",
     "Indexed Yelp drywall-repair page lists The Crew Stucco & Plastering at 4.3 across about 7 reviews with drywall repair.",
     ["No identity or license captured.", "Small review sample.", "Plaster/stucco-led; confirm drywall/trade license."]),
    ("certapro", "CertaPro Painters of San Francisco", 99,
     "CertaPro Painters of San Francisco · Outer Sunset service area · Drywall Repair",
     "outer", "Business lists Outer Sunset among service areas; offers drywall repair and EPA Lead Certified renovation.",
     "Business marketing page lists Outer Sunset among CertaPro San Francisco service areas and offers drywall repair.",
     ["Franchise operation; confirm the local franchise's license and insurance.", "Drywall scope — finish phase only.", "No exact seized-overflow extraction case verified."],
     dict(website="https://certapro.com/san-francisco/professional-painters-outer-sunset/", websiteSource=99)),
    ("je-carpentry", "J E Carpentry & Handy Man", 97,
     "J E Carpentry & Handy Man 4.7 (37 reviews)",
     "unknown", "Appears on the indexed Outer Sunset handyman results page; base not established.",
     "Indexed Yelp handyman page lists J E Carpentry & Handy Man at 4.7 across about 37 reviews.",
     ["No identity or license captured.", "Handyman/carpentry scope — hatch carpentry only.", "Not a plumbing-code contractor per available evidence."]),
    ("tal-handyman", "Tal Handyman Services", 97,
     "Tal Handyman Services 3.9 (16 reviews)",
     "unknown", "Appears on the indexed Outer Sunset handyman results page; base not established.",
     "Indexed Yelp handyman page lists Tal Handyman Services at 3.9 across about 16 reviews.",
     ["No identity or license captured.", "Mid rating; handyman scope — hatch phase only.", "Not a plumbing-code contractor."]),
    ("handy-helper", "Handy Helper", 97,
     "Handy Helper 5.0 (18 reviews)",
     "unknown", "Appears on the indexed Outer Sunset handyman results page; base not established.",
     "Indexed Yelp handyman page lists Handy Helper at 5.0 across about 18 reviews.",
     ["No identity or license captured.", "Handyman scope — hatch phase only.", "Not a plumbing-code contractor."]),
    ("longshore-handyman", "Longshore Handyman", 97,
     "Longshore Handyman 4.8 (56 reviews)",
     "unknown", "Appears on the indexed Outer Sunset handyman results page; base not established.",
     "Indexed Yelp handyman page lists Longshore Handyman at 4.8 across about 56 reviews.",
     ["No identity or license captured.", "Handyman scope — hatch phase only.", "Not a plumbing-code contractor."]),
    ("guerra-handyman", "Guerra Handyman", 97,
     "Guerra Handyman 5.0 (4 reviews)",
     "unknown", "Appears on the indexed Outer Sunset handyman results page; base not established.",
     "Indexed Yelp handyman page lists Guerra Handyman at 5.0 across about 4 reviews (Serving Sunnyvale per listing text).",
     ["Very small review sample.", "Listing text shows Sunnyvale service; SF Outer Sunset dispatch unconfirmed.", "Not a plumbing-code contractor."]),
    ("handyfix", "HandyFix", 97,
     "HandyFix 5.0 (1 review)",
     "unknown", "Appears on the indexed Outer Sunset handyman results page; base not established.",
     "Indexed Yelp handyman page lists HandyFix at 5.0 across 1 review (Serving Fremont per listing text).",
     ["Single review; listing shows Fremont service.", "SF Outer Sunset dispatch unconfirmed.", "Not a plumbing-code contractor."]),
    ("abc-maintenance", "ABC Maintenance & Handyman Services", 97,
     "ABC Maintenance & Handyman Services 5.0 (23 reviews)",
     "unknown", "Appears on the indexed Outer Sunset handyman results page; base not established.",
     "Indexed Yelp handyman page lists ABC Maintenance & Handyman Services at 5.0 across about 23 reviews.",
     ["No identity or license captured.", "Handyman scope — hatch phase only.", "Not a plumbing-code contractor."]),
    ("speer-handyman", "Speer Handyman Services", 97,
     "Speer Handyman Services 4.9 (37 reviews)",
     "unknown", "Appears on the indexed Outer Sunset handyman results page; base not established.",
     "Indexed Yelp handyman page lists Speer Handyman Services at 4.9 across about 37 reviews.",
     ["No identity or license captured.", "Handyman scope — hatch phase only.", "Not a plumbing-code contractor."]),

    # ---- General contractors / bathroom remodel ----
    ("kh-construction", "K&H Construction Development", 93,
     "K&H Construction Development 5.0 (23 reviews) Outer Sunset · bathroom remodel",
     "outer", "Indexed Yelp contractor page lists K&H in Outer Sunset with a bathroom/kitchen remodel portfolio.",
     "Indexed Yelp contractor page lists K&H Construction Development at 5.0 across about 23 reviews in Outer Sunset with bathroom remodels.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "No exact seized-overflow extraction case verified."],
     dict(reviewIds=["R30", "R31"])),
    ("a2z-remodeling", "A2Z Remodeling", 93,
     "A2Z Remodeling 4.9 (108 reviews) Serving San Francisco",
     "sf", "Indexed Yelp contractor page; Serving San Francisco and the Surrounding Area.",
     "Indexed Yelp contractor page lists A2Z Remodeling at 4.9 across about 108 reviews serving San Francisco.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "Outer Sunset dispatch not separately confirmed."]),
    ("de-nola", "Richard De Nola", 93,
     "Richard De Nola 5.0 (5 reviews) 30 years in business",
     "sf", "Indexed Yelp contractor page; Serving San Francisco; 30 years in business.",
     "Indexed Yelp contractor page lists Richard De Nola at 5.0 across 5 reviews, 30 years in business, serving San Francisco.",
     ["Small review sample.", "No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting."],
     dict(reviewIds=["R??"])),  # placeholder removed below
    ("be-home", "Be Home Remodeling", 93,
     "Be Home Remodeling 5.0 (24 reviews) Serving San Francisco",
     "sf", "Indexed Yelp contractor page; Serving San Francisco; family-owned.",
     "Indexed Yelp contractor page lists Be Home Remodeling at 5.0 across about 24 reviews serving San Francisco.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "Outer Sunset dispatch not separately confirmed."]),
    ("oshaughnessy", "O Shaughnessy Construction", 93,
     "O Shaughnessy Construction 5.0 (19 reviews) Serving San Francisco",
     "sf", "Indexed Yelp contractor page; Serving San Francisco.",
     "Indexed Yelp contractor page lists O Shaughnessy Construction at 5.0 across about 19 reviews serving San Francisco.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "Outer Sunset dispatch not separately confirmed."]),
    ("pacific-construction", "Pacific Construction", 94,
     "Pacific Construction 4.7 (14 reviews) Serving San Francisco",
     "sf", "Indexed Yelp bathroom-remodeling page; Serving San Francisco.",
     "Indexed Yelp bathroom-remodeling page lists Pacific Construction at 4.7 across about 14 reviews serving San Francisco.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "Outer Sunset dispatch not separately confirmed."]),
    ("triond", "Triond Remodeling", 94,
     "Triond Remodeling 4.7 (31 reviews) Serving San Francisco",
     "sf", "Indexed Yelp bathroom-remodeling page; Serving San Francisco.",
     "Indexed Yelp bathroom-remodeling page lists Triond Remodeling at 4.7 across about 31 reviews serving San Francisco.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "Outer Sunset dispatch not separately confirmed."]),
    ("fonseca", "Fonseca Marble and Tile", 94,
     "Fonseca Marble and Tile 4.8 (99 reviews) Serving San Francisco",
     "sf", "Indexed Yelp bathroom-remodeling page; Serving San Francisco (tile specialty).",
     "Indexed Yelp bathroom-remodeling page lists Fonseca Marble and Tile at 4.8 across about 99 reviews serving San Francisco.",
     ["Tile specialty; confirm GC license for structural/plumbing phases.", "No CSLB identity/class captured in this pass.", "Outer Sunset dispatch not separately confirmed."]),
    ("shower-pan-king", "The Shower Pan King", 94,
     "The Shower Pan King 4.8 (66 reviews) · dry rot extended into bathroom floor",
     "sf", "Indexed Yelp bathroom-remodeling page; Serving San Francisco.",
     "Indexed Yelp bathroom-remodeling page lists The Shower Pan King at 4.8 across about 66 reviews, with a review mentioning dry rot in a bathroom floor.",
     ["Niche shower-pan/tile scope; confirm GC license for structural/plumbing phases.", "No CSLB identity/class captured in this pass.", "Outer Sunset dispatch not separately confirmed."],
     dict(reviewIds=["R39"])),
    ("ee-general", "E&E General Construction", 94,
     "E&E General Construction 4.7 (37 reviews) · ADUs, additions, remodels",
     "sf", "Indexed Yelp bathroom-remodeling page; Serving San Francisco.",
     "Indexed Yelp bathroom-remodeling page lists E&E General Construction at 4.7 across about 37 reviews focusing on ADUs and remodels.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "Outer Sunset dispatch not separately confirmed."]),
    ("quality-painting", "Quality Painting & Construction", 93,
     "Quality Painting & Construction 5.0 (32 reviews) Serving San Francisco",
     "sf", "Indexed Yelp contractor page; Serving San Francisco.",
     "Indexed Yelp contractor page lists Quality Painting & Construction at 5.0 across about 32 reviews serving San Francisco.",
     ["Painting-led; confirm construction license for structural phases.", "No CSLB identity/class captured in this pass.", "Outer Sunset dispatch not separately confirmed."]),
    ("we-do-construction", "We Do Construction", 93,
     "We Do Construction 5.0 (101 reviews) Serving San Francisco",
     "sf", "Indexed Yelp contractor page; Serving San Francisco.",
     "Indexed Yelp contractor page lists We Do Construction at 5.0 across about 101 reviews serving San Francisco.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "Outer Sunset dispatch not separately confirmed."]),
    ("gallos", "Gallos Quality Construction", 93,
     "Gallos Quality Construction 5.0 (15 reviews) Serving San Francisco",
     "sf", "Indexed Yelp contractor page; Serving San Francisco.",
     "Indexed Yelp contractor page lists Gallos Quality Construction at 5.0 across about 15 reviews serving San Francisco.",
     ["No CSLB identity/class captured in this pass.", "Small-ish review sample.", "Outer Sunset dispatch not separately confirmed."]),
    ("ml-construction", "M & L Construction", 93,
     "M & L Construction 4.7 (134 reviews) · 0.9 Miles",
     "sunset", "Indexed Yelp contractor page shows M & L Construction about 0.9 miles from the referenced Sunset point.",
     "Indexed Yelp contractor page lists M & L Construction at 4.7 across about 134 reviews, shown about 0.9 miles from the Sunset reference point.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "Exact Outer Sunset block not confirmed."],
     dict(reviewIds=["R33"])),
    ("valex", "Valex Construction", 94,
     "Valex Construction 4.8 (58 reviews) Serving San Francisco",
     "sf", "Indexed Yelp bathroom-remodeling page; Serving San Francisco.",
     "Indexed Yelp bathroom-remodeling page lists Valex Construction at 4.8 across about 58 reviews serving San Francisco.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "Outer Sunset dispatch not separately confirmed."]),
    ("reliable-construction", "Reliable Construction", 93,
     "Reliable Construction 4.9 (65 reviews) · bathroom remodel",
     "sf", "Indexed Yelp contractor page; Serving San Francisco; 30 years in business.",
     "Indexed Yelp contractor page lists Reliable Construction at 4.9 across about 65 reviews with bathroom-remodel work, 30 years in business.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "Outer Sunset dispatch not separately confirmed."]),
    ("master-v", "Master-V Construction", 94,
     "Master-V Construction 5.0 (8 reviews) · 2070 45th Ave Outer Sunset",
     "outer", "Indexed Yelp profile lists 2070 45th Ave, San Francisco 94116 (Outer Sunset) with bathroom-remodel work.",
     "Indexed Yelp bathroom-remodeling profile lists Master-V Construction at 5.0 across 8 reviews with a 2070 45th Ave Outer Sunset address.",
     ["Small review sample.", "No CSLB identity/class captured in this pass.", "Confirm GC license and insurance before booking."],
     dict(reviewIds=["R32"])),
    ("peters-design", "Peters Design-Build", 93,
     "Peters Design-Build 4.8 (16 reviews) Serving San Francisco",
     "sf", "Indexed Yelp contractor page; Serving San Francisco.",
     "Indexed Yelp contractor page lists Peters Design-Build at 4.8 across about 16 reviews serving San Francisco.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "Outer Sunset dispatch not separately confirmed."]),
    ("remodeling-heroes", "Remodeling Heroes", 93,
     "Remodeling Heroes 4.4 (93 reviews) · 1920s house bathroom",
     "sf", "Indexed Yelp contractor page; Serving San Francisco; 15 years in business.",
     "Indexed Yelp contractor page lists Remodeling Heroes at 4.4 across about 93 reviews, including a 1920s-house bathroom remodel.",
     ["No CSLB identity/class captured in this pass.", "GC scope must be confirmed for plumbing sub-contracting.", "Older-home experience is relevant but not seized-overflow proof."]),

    # ---- Water damage / restoration (ceiling opening + dryout) ----
    ("allied-restoration", "Allied Restoration Company", 100,
     "Allied Restoration Company · 222 Columbus Ave #201, San Francisco · (415) 529-5637",
     "sf", "SF office at 222 Columbus Ave per the business's water-damage page; markets ceiling/wall opening for dryout.",
     "Business water-damage page lists an SF office at 222 Columbus Ave and describes opening walls/ceilings for drying after leaks.",
     ["No CSLB identity/class captured in this pass.", "Restoration scope; plumbing extraction remains a separate C36 trade.", "Outer Sunset dispatch not separately confirmed."],
     dict(phone="415-529-5637", phoneSource=100,
          website="https://www.sanfranciscofloodrepair.com/water-damage-in-outer-sunset/", websiteSource=100)),
    ("gcd-restoration", "GCD Restoration", 95,
     "GCD Restoration 5.0 (108 reviews) Daly City · water damage restoration",
     "sf", "Indexed Yelp water-damage page; base Daly City; Serving Daly City and surrounding area.",
     "Indexed Yelp water-damage page lists GCD Restoration at 5.0 across about 108 reviews based in Daly City.",
     ["Daly City base; SF Outer Sunset dispatch unconfirmed.", "No CSLB identity/class captured in this pass.", "Restoration scope; plumbing extraction is a separate trade."],
     dict(reviewIds=["R38"])),
    ("swift-restoration", "Swift Restoration", 95,
     "Swift Restoration 4.8 (181 reviews) Serving San Francisco",
     "sf", "Indexed Yelp water-damage page; Serving San Francisco.",
     "Indexed Yelp water-damage page lists Swift Restoration at 4.8 across about 181 reviews serving San Francisco.",
     ["No CSLB identity/class captured in this pass.", "Restoration scope; plumbing extraction is a separate trade.", "Outer Sunset dispatch not separately confirmed."],
     dict(reviewIds=["R36"])),
    ("fire-water-recovery", "Fire & Water Damage Recovery", 95,
     "Fire & Water Damage Recovery 4.7 (140 reviews) Serving San Francisco · women-owned",
     "sf", "Indexed Yelp water-damage page; Serving San Francisco; women-owned; 24/7.",
     "Indexed Yelp water-damage page lists Fire & Water Damage Recovery at 4.7 across about 140 reviews serving San Francisco.",
     ["No CSLB identity/class captured in this pass.", "Restoration scope; plumbing extraction is a separate trade.", "Outer Sunset dispatch not separately confirmed."],
     dict(reviewIds=["R37"])),
    ("bio-911", "Bio 911", 95,
     "Bio 911 4.9 (27 reviews) Serving San Francisco · drywall repair",
     "sf", "Indexed Yelp water-damage page; Serving San Francisco; mentions drywall repair.",
     "Indexed Yelp water-damage page lists Bio 911 at 4.9 across about 27 reviews serving San Francisco with drywall repair.",
     ["No CSLB identity/class captured in this pass.", "Restoration/drywall scope; plumbing extraction is a separate trade.", "Outer Sunset dispatch not separately confirmed."]),
    ("ez-mold", "Ez MoldRemoval", 95,
     "Ez MoldRemoval 5.0 (1 review) · 1600 47th Ave Outer Sunset",
     "outer", "Indexed Yelp water-damage result lists 1600 47th Ave, San Francisco 94122 (Outer Sunset).",
     "Indexed Yelp water-damage result lists Ez MoldRemoval with a 1600 47th Ave Outer Sunset address.",
     ["Single review; verify identity and license.", "Mold-remediation scope; confirm general-building license for repairs.", "Outer Sunset address is a directory footprint until confirmed."]),
    ("reactic", "Reactic Restoration", 96,
     "Reactic Restoration 5.0 (10 reviews) Serving San Francisco · rebuilding the wall afterwards",
     "sf", "Indexed Yelp water-extraction page; Serving San Francisco.",
     "Indexed Yelp water-extraction page lists Reactic Restoration at 5.0 across about 10 reviews serving San Francisco, including wall rebuild after mold.",
     ["No CSLB identity/class captured in this pass.", "Small review sample.", "Restoration scope; plumbing extraction is a separate trade."],
     dict(reviewIds=["R??"])),  # placeholder removed below
    ("bay-mold", "Bay Mold", 95,
     "Bay Mold 4.3 (46 reviews) Serving San Francisco · 23 years in business",
     "sf", "Indexed Yelp water-damage page; Serving San Francisco; 23 years in business.",
     "Indexed Yelp water-damage page lists Bay Mold at 4.3 across about 46 reviews serving San Francisco.",
     ["No CSLB identity/class captured in this pass.", "Mold-remediation scope; confirm general-building license for repairs.", "Outer Sunset dispatch not separately confirmed."]),
]

# strip placeholder reviewIds
for r in ROWS:
    if len(r) == 8 and isinstance(r[7], dict) and r[7].get("reviewIds") == ["R??"]:
        r[7].pop("reviewIds")

def make_business(row):
    id, name, src, excerpt, area, areaText, discovery_text, extra_gaps = row[:8]
    kw = row[8] if len(row) > 8 and isinstance(row[8], dict) else {}
    claims = [{
        "field": "Discovery",
        "text": discovery_text,
        "source": src,
        "excerpt": excerpt,
    }]
    b = {
        "id": id,
        "name": name,
        "website": kw.get("website"),
        "websiteSource": kw.get("websiteSource"),
        "status": "research",
        "area": area,
        "areaText": areaText,
        "license": None,
        "phone": kw.get("phone"),
        "phoneSource": kw.get("phoneSource"),
        "claims": claims,
        "flags": kw.get("flags", []),
        "reviewIds": kw.get("reviewIds", []),
        "exactMatch": False,
        "master": False,
        "checkedAt": RESEARCHED,
        "gaps": ["No exact seized-overflow extraction case verified."] + list(extra_gaps),
    }
    return b

businesses = [make_business(r) for r in ROWS]

REVIEWS = [
    {"id": "R30", "business": "kh-construction", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed", "quote": "We chose K&H for our Bathroom remodel including adding a small laundry closet and had a great...",
     "analysis": "Indexed Yelp quote describing a bathroom remodel by K&H in the Outer Sunset results; supports bath/remodel capability, not seized-overflow extraction.",
     "theme": "Bath remodel", "source": 93, "access": "search-extract", "identity": "indexed", "negative": False,
     "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R31", "business": "kh-construction", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed", "quote": "K&H quoted and worked on a series of roof leaks and internal ceiling damage in our bedroom and media room...",
     "analysis": "Indexed quote shows K&H handling internal ceiling damage repair — directly relevant to the ceiling-opening/restore phase of the target job.",
     "theme": "Ceiling repair", "source": 93, "access": "search-extract", "identity": "indexed", "negative": False,
     "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R32", "business": "master-v", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed", "quote": "Very professional, great communication, and honest. Val and Alex completed my bathroom remodel on...",
     "analysis": "Indexed Yelp quote for a bathroom remodel by a firm whose profile lists a 2070 45th Ave Outer Sunset address; supports local GC capability.",
     "theme": "Bath remodel", "source": 94, "access": "search-extract", "identity": "indexed", "negative": False,
     "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R33", "business": "ml-construction", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed", "quote": "I will never go to any other contractor for our home remodel needs.",
     "analysis": "Indexed loyalty quote; no task detail relevant to seized overflow extraction. Shows repeat-use satisfaction only.",
     "theme": "General quality", "source": 93, "access": "search-extract", "identity": "indexed", "negative": False,
     "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R34", "business": "toms-painters", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed", "quote": "The painting and drywall results were high quality.",
     "analysis": "Indexed quote about drywall + painting quality; relevant to the finish/hatch-closing phase of the target job.",
     "theme": "Drywall finishing", "source": 91, "access": "search-extract", "identity": "indexed", "negative": False,
     "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R35", "business": "amadors-drywall", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed", "quote": "I hired Amador's to install drywall & insulation for the entire rear portion of our two story home",
     "analysis": "Indexed quote about whole-home drywall/insulation install; demonstrates drywall capacity but not a small access-hatch patch.",
     "theme": "Drywall install", "source": 91, "access": "search-extract", "identity": "indexed", "negative": False,
     "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R36", "business": "swift-restoration", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed", "quote": "I highly recommend Swift Restoration if you have water damage in home and need help.",
     "analysis": "Indexed endorsement for water-damage restoration; supports the ceiling-dryout phase of the target job. No plumbing content.",
     "theme": "Water damage", "source": 95, "access": "search-extract", "identity": "indexed", "negative": False,
     "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R37", "business": "fire-water-recovery", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed", "quote": "my investment property flooded. The light well flooded the lower bathroom. Unhappy tenant.",
     "analysis": "Indexed review describes a flooded lower bathroom in an investment property — analogous to the in-law-unit-below scenario; restoration scope, not plumbing extraction.",
     "theme": "Water damage", "source": 95, "access": "search-extract", "identity": "indexed", "negative": False,
     "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R38", "business": "gcd-restoration", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed", "quote": "When all is said and done, I feel Manny and the GCD team did a great job",
     "analysis": "Indexed praise for GCD restoration work; Daly City base, SF dispatch unconfirmed. Restoration scope only.",
     "theme": "Water damage", "source": 95, "access": "search-extract", "identity": "indexed", "negative": False,
     "checkedAt": RESEARCHED, "exactTask": False},
    {"id": "R39", "business": "shower-pan-king", "platform": "Yelp", "author": "Not shown in indexed extract",
     "published": "Not displayed", "quote": "the dry rot extended into the bathroom floor, and Dave did an excellent job of...",
     "analysis": "Indexed quote about dry-rot repair extending into a bathroom floor — adjacent to subfloor/access work, not overflow mechanism.",
     "theme": "Dry rot", "source": 94, "access": "search-extract", "identity": "indexed", "negative": False,
     "checkedAt": RESEARCHED, "exactTask": False},
]

wave = {"businesses": businesses, "sources": SOURCES, "reviews": REVIEWS}
out = ROOT / "data" / "wave3.json"
out.write_text(json.dumps(wave, indent=1, ensure_ascii=False) + "\n")
print(f"wrote {out}: {len(businesses)} businesses, {len(SOURCES)} sources, {len(REVIEWS)} reviews")
